#include "cctk.h"

module qlm_emd_variables
  use classify
  implicit none
  public
  save
  CCTK_REAL, allocatable, dimension(:,:) :: &
       qlm_emd_gxx, qlm_emd_gxy, qlm_emd_gxz, qlm_emd_gyy, qlm_emd_gyz, qlm_emd_gzz, &
       qlm_emd_dgxxx, qlm_emd_dgxyx, qlm_emd_dgxzx, qlm_emd_dgyyx, qlm_emd_dgyzx, qlm_emd_dgzzx, &
       qlm_emd_dgxxy, qlm_emd_dgxyy, qlm_emd_dgxzy, qlm_emd_dgyyy, qlm_emd_dgyzy, qlm_emd_dgzzy, &
       qlm_emd_dgxxz, qlm_emd_dgxyz, qlm_emd_dgxzz, qlm_emd_dgyyz, qlm_emd_dgyzz, qlm_emd_dgzzz, &
       qlm_emd_ddgxxxx, qlm_emd_ddgxyxx, qlm_emd_ddgxzxx, qlm_emd_ddgyyxx, qlm_emd_ddgyzxx, qlm_emd_ddgzzxx, &
       qlm_emd_ddgxxxy, qlm_emd_ddgxyxy, qlm_emd_ddgxzxy, qlm_emd_ddgyyxy, qlm_emd_ddgyzxy, qlm_emd_ddgzzxy, &
       qlm_emd_ddgxxxz, qlm_emd_ddgxyxz, qlm_emd_ddgxzxz, qlm_emd_ddgyyxz, qlm_emd_ddgyzxz, qlm_emd_ddgzzxz, &
       qlm_emd_ddgxxyy, qlm_emd_ddgxyyy, qlm_emd_ddgxzyy, qlm_emd_ddgyyyy, qlm_emd_ddgyzyy, qlm_emd_ddgzzyy, &
       qlm_emd_ddgxxyz, qlm_emd_ddgxyyz, qlm_emd_ddgxzyz, qlm_emd_ddgyyyz, qlm_emd_ddgyzyz, qlm_emd_ddgzzyz, &
       qlm_emd_ddgxxzz, qlm_emd_ddgxyzz, qlm_emd_ddgxzzz, qlm_emd_ddgyyzz, qlm_emd_ddgyzzz, qlm_emd_ddgzzzz, &
       qlm_emd_kxx, qlm_emd_kxy, qlm_emd_kxz, qlm_emd_kyy, qlm_emd_kyz, qlm_emd_kzz, &
       qlm_emd_dkxxx, qlm_emd_dkxyx, qlm_emd_dkxzx, qlm_emd_dkyyx, qlm_emd_dkyzx, qlm_emd_dkzzx, &
       qlm_emd_dkxxy, qlm_emd_dkxyy, qlm_emd_dkxzy, qlm_emd_dkyyy, qlm_emd_dkyzy, qlm_emd_dkzzy, &
       qlm_emd_dkxxz, qlm_emd_dkxyz, qlm_emd_dkxzz, qlm_emd_dkyyz, qlm_emd_dkyzz, qlm_emd_dkzzz, &
       qlm_emd_alpha, &
       qlm_emd_betax, qlm_emd_betay, qlm_emd_betaz, &
       qlm_emd_ttt, &
       qlm_emd_ttx, qlm_emd_tty, qlm_emd_ttz, &
       qlm_emd_txx, qlm_emd_txy, qlm_emd_txz, qlm_emd_tyy, qlm_emd_tyz, qlm_emd_tzz, &
       qlm_emd_ex, qlm_emd_ey, qlm_emd_ez
  CCTK_REAL, allocatable, dimension(:,:) :: &
       qlm_emd_dqttt, qlm_emd_dqtpt, qlm_emd_dqppt, qlm_emd_dqttp, qlm_emd_dqtpp, qlm_emd_dqppp
  
  CCTK_REAL, allocatable, dimension(:,:) :: &
       qlm_emd_spin_density
  
  type tetrad_derivs
     ! nabla_ll(a,b) = D_b l_a
     CCTK_REAL    :: nabla_ll(0:3,0:3)
     CCTK_REAL    :: nabla_nn(0:3,0:3)
     CCTK_COMPLEX :: nabla_mm(0:3,0:3)
  end type tetrad_derivs
  type(tetrad_derivs), allocatable, dimension(:,:) :: qlm_emd_tetrad_derivs
  
contains
  
  subroutine allocate_variables(ntheta, nphi)
    integer,   intent(in) :: ntheta, nphi
    CCTK_REAL, parameter  :: zero = 0
    integer,   parameter  :: rk = kind(zero)
    type(tetrad_derivs)   :: tetrad_derivs_nan
    
    allocate(qlm_emd_gxx(ntheta,nphi))
    allocate(qlm_emd_gxy(ntheta,nphi))
    allocate(qlm_emd_gxz(ntheta,nphi))
    allocate(qlm_emd_gyy(ntheta,nphi))
    allocate(qlm_emd_gyz(ntheta,nphi))
    allocate(qlm_emd_gzz(ntheta,nphi))
    allocate(qlm_emd_dgxxx(ntheta,nphi))
    allocate(qlm_emd_dgxyx(ntheta,nphi))
    allocate(qlm_emd_dgxzx(ntheta,nphi))
    allocate(qlm_emd_dgyyx(ntheta,nphi))
    allocate(qlm_emd_dgyzx(ntheta,nphi))
    allocate(qlm_emd_dgzzx(ntheta,nphi))
    allocate(qlm_emd_dgxxy(ntheta,nphi))
    allocate(qlm_emd_dgxyy(ntheta,nphi))
    allocate(qlm_emd_dgxzy(ntheta,nphi))
    allocate(qlm_emd_dgyyy(ntheta,nphi))
    allocate(qlm_emd_dgyzy(ntheta,nphi))
    allocate(qlm_emd_dgzzy(ntheta,nphi))
    allocate(qlm_emd_dgxxz(ntheta,nphi))
    allocate(qlm_emd_dgxyz(ntheta,nphi))
    allocate(qlm_emd_dgxzz(ntheta,nphi))
    allocate(qlm_emd_dgyyz(ntheta,nphi))
    allocate(qlm_emd_dgyzz(ntheta,nphi))
    allocate(qlm_emd_dgzzz(ntheta,nphi))
    allocate(qlm_emd_ddgxxxx(ntheta,nphi))
    allocate(qlm_emd_ddgxyxx(ntheta,nphi))
    allocate(qlm_emd_ddgxzxx(ntheta,nphi))
    allocate(qlm_emd_ddgyyxx(ntheta,nphi))
    allocate(qlm_emd_ddgyzxx(ntheta,nphi))
    allocate(qlm_emd_ddgzzxx(ntheta,nphi))
    allocate(qlm_emd_ddgxxxy(ntheta,nphi))
    allocate(qlm_emd_ddgxyxy(ntheta,nphi))
    allocate(qlm_emd_ddgxzxy(ntheta,nphi))
    allocate(qlm_emd_ddgyyxy(ntheta,nphi))
    allocate(qlm_emd_ddgyzxy(ntheta,nphi))
    allocate(qlm_emd_ddgzzxy(ntheta,nphi))
    allocate(qlm_emd_ddgxxxz(ntheta,nphi))
    allocate(qlm_emd_ddgxyxz(ntheta,nphi))
    allocate(qlm_emd_ddgxzxz(ntheta,nphi))
    allocate(qlm_emd_ddgyyxz(ntheta,nphi))
    allocate(qlm_emd_ddgyzxz(ntheta,nphi))
    allocate(qlm_emd_ddgzzxz(ntheta,nphi))
    allocate(qlm_emd_ddgxxyy(ntheta,nphi))
    allocate(qlm_emd_ddgxyyy(ntheta,nphi))
    allocate(qlm_emd_ddgxzyy(ntheta,nphi))
    allocate(qlm_emd_ddgyyyy(ntheta,nphi))
    allocate(qlm_emd_ddgyzyy(ntheta,nphi))
    allocate(qlm_emd_ddgzzyy(ntheta,nphi))
    allocate(qlm_emd_ddgxxyz(ntheta,nphi))
    allocate(qlm_emd_ddgxyyz(ntheta,nphi))
    allocate(qlm_emd_ddgxzyz(ntheta,nphi))
    allocate(qlm_emd_ddgyyyz(ntheta,nphi))
    allocate(qlm_emd_ddgyzyz(ntheta,nphi))
    allocate(qlm_emd_ddgzzyz(ntheta,nphi))
    allocate(qlm_emd_ddgxxzz(ntheta,nphi))
    allocate(qlm_emd_ddgxyzz(ntheta,nphi))
    allocate(qlm_emd_ddgxzzz(ntheta,nphi))
    allocate(qlm_emd_ddgyyzz(ntheta,nphi))
    allocate(qlm_emd_ddgyzzz(ntheta,nphi))
    allocate(qlm_emd_ddgzzzz(ntheta,nphi))
    allocate(qlm_emd_kxx(ntheta,nphi))
    allocate(qlm_emd_kxy(ntheta,nphi))
    allocate(qlm_emd_kxz(ntheta,nphi))
    allocate(qlm_emd_kyy(ntheta,nphi))
    allocate(qlm_emd_kyz(ntheta,nphi))
    allocate(qlm_emd_kzz(ntheta,nphi))
    allocate(qlm_emd_dkxxx(ntheta,nphi))
    allocate(qlm_emd_dkxyx(ntheta,nphi))
    allocate(qlm_emd_dkxzx(ntheta,nphi))
    allocate(qlm_emd_dkyyx(ntheta,nphi))
    allocate(qlm_emd_dkyzx(ntheta,nphi))
    allocate(qlm_emd_dkzzx(ntheta,nphi))
    allocate(qlm_emd_dkxxy(ntheta,nphi))
    allocate(qlm_emd_dkxyy(ntheta,nphi))
    allocate(qlm_emd_dkxzy(ntheta,nphi))
    allocate(qlm_emd_dkyyy(ntheta,nphi))
    allocate(qlm_emd_dkyzy(ntheta,nphi))
    allocate(qlm_emd_dkzzy(ntheta,nphi))
    allocate(qlm_emd_dkxxz(ntheta,nphi))
    allocate(qlm_emd_dkxyz(ntheta,nphi))
    allocate(qlm_emd_dkxzz(ntheta,nphi))
    allocate(qlm_emd_dkyyz(ntheta,nphi))
    allocate(qlm_emd_dkyzz(ntheta,nphi))
    allocate(qlm_emd_dkzzz(ntheta,nphi))
    allocate(qlm_emd_alpha(ntheta,nphi))
    allocate(qlm_emd_betax(ntheta,nphi))
    allocate(qlm_emd_betay(ntheta,nphi))
    allocate(qlm_emd_betaz(ntheta,nphi))
    allocate(qlm_emd_ttt(ntheta,nphi))
    allocate(qlm_emd_ttx(ntheta,nphi))
    allocate(qlm_emd_tty(ntheta,nphi))
    allocate(qlm_emd_ttz(ntheta,nphi))
    allocate(qlm_emd_txx(ntheta,nphi))
    allocate(qlm_emd_txy(ntheta,nphi))
    allocate(qlm_emd_txz(ntheta,nphi))
    allocate(qlm_emd_tyy(ntheta,nphi))
    allocate(qlm_emd_tyz(ntheta,nphi))
    allocate(qlm_emd_tzz(ntheta,nphi))
    allocate(qlm_emd_ex(ntheta,nphi))
    allocate(qlm_emd_ey(ntheta,nphi))
    allocate(qlm_emd_ez(ntheta,nphi))
    
    allocate(qlm_emd_dqttt(ntheta,nphi))
    allocate(qlm_emd_dqtpt(ntheta,nphi))
    allocate(qlm_emd_dqppt(ntheta,nphi))
    allocate(qlm_emd_dqttp(ntheta,nphi))
    allocate(qlm_emd_dqtpp(ntheta,nphi))
    allocate(qlm_emd_dqppp(ntheta,nphi))
    
    allocate(qlm_emd_tetrad_derivs(ntheta,nphi))
    
    allocate(qlm_emd_spin_density(ntheta,nphi))
    
    qlm_emd_gxx = TAT_nan()
    qlm_emd_gxy = TAT_nan()
    qlm_emd_gxz = TAT_nan()
    qlm_emd_gyy = TAT_nan()
    qlm_emd_gyz = TAT_nan()
    qlm_emd_gzz = TAT_nan()
    qlm_emd_dgxxx = TAT_nan()
    qlm_emd_dgxyx = TAT_nan()
    qlm_emd_dgxzx = TAT_nan()
    qlm_emd_dgyyx = TAT_nan()
    qlm_emd_dgyzx = TAT_nan()
    qlm_emd_dgzzx = TAT_nan()
    qlm_emd_dgxxy = TAT_nan()
    qlm_emd_dgxyy = TAT_nan()
    qlm_emd_dgxzy = TAT_nan()
    qlm_emd_dgyyy = TAT_nan()
    qlm_emd_dgyzy = TAT_nan()
    qlm_emd_dgzzy = TAT_nan()
    qlm_emd_dgxxz = TAT_nan()
    qlm_emd_dgxyz = TAT_nan()
    qlm_emd_dgxzz = TAT_nan()
    qlm_emd_dgyyz = TAT_nan()
    qlm_emd_dgyzz = TAT_nan()
    qlm_emd_dgzzz = TAT_nan()
    qlm_emd_ddgxxxx = TAT_nan()
    qlm_emd_ddgxyxx = TAT_nan()
    qlm_emd_ddgxzxx = TAT_nan()
    qlm_emd_ddgyyxx = TAT_nan()
    qlm_emd_ddgyzxx = TAT_nan()
    qlm_emd_ddgzzxx = TAT_nan()
    qlm_emd_ddgxxxy = TAT_nan()
    qlm_emd_ddgxyxy = TAT_nan()
    qlm_emd_ddgxzxy = TAT_nan()
    qlm_emd_ddgyyxy = TAT_nan()
    qlm_emd_ddgyzxy = TAT_nan()
    qlm_emd_ddgzzxy = TAT_nan()
    qlm_emd_ddgxxxz = TAT_nan()
    qlm_emd_ddgxyxz = TAT_nan()
    qlm_emd_ddgxzxz = TAT_nan()
    qlm_emd_ddgyyxz = TAT_nan()
    qlm_emd_ddgyzxz = TAT_nan()
    qlm_emd_ddgzzxz = TAT_nan()
    qlm_emd_ddgxxyy = TAT_nan()
    qlm_emd_ddgxyyy = TAT_nan()
    qlm_emd_ddgxzyy = TAT_nan()
    qlm_emd_ddgyyyy = TAT_nan()
    qlm_emd_ddgyzyy = TAT_nan()
    qlm_emd_ddgzzyy = TAT_nan()
    qlm_emd_ddgxxyz = TAT_nan()
    qlm_emd_ddgxyyz = TAT_nan()
    qlm_emd_ddgxzyz = TAT_nan()
    qlm_emd_ddgyyyz = TAT_nan()
    qlm_emd_ddgyzyz = TAT_nan()
    qlm_emd_ddgzzyz = TAT_nan()
    qlm_emd_ddgxxzz = TAT_nan()
    qlm_emd_ddgxyzz = TAT_nan()
    qlm_emd_ddgxzzz = TAT_nan()
    qlm_emd_ddgyyzz = TAT_nan()
    qlm_emd_ddgyzzz = TAT_nan()
    qlm_emd_ddgzzzz = TAT_nan()
    qlm_emd_kxx = TAT_nan()
    qlm_emd_kxy = TAT_nan()
    qlm_emd_kxz = TAT_nan()
    qlm_emd_kyy = TAT_nan()
    qlm_emd_kyz = TAT_nan()
    qlm_emd_kzz = TAT_nan()
    qlm_emd_dkxxx = TAT_nan()
    qlm_emd_dkxyx = TAT_nan()
    qlm_emd_dkxzx = TAT_nan()
    qlm_emd_dkyyx = TAT_nan()
    qlm_emd_dkyzx = TAT_nan()
    qlm_emd_dkzzx = TAT_nan()
    qlm_emd_dkxxy = TAT_nan()
    qlm_emd_dkxyy = TAT_nan()
    qlm_emd_dkxzy = TAT_nan()
    qlm_emd_dkyyy = TAT_nan()
    qlm_emd_dkyzy = TAT_nan()
    qlm_emd_dkzzy = TAT_nan()
    qlm_emd_dkxxz = TAT_nan()
    qlm_emd_dkxyz = TAT_nan()
    qlm_emd_dkxzz = TAT_nan()
    qlm_emd_dkyyz = TAT_nan()
    qlm_emd_dkyzz = TAT_nan()
    qlm_emd_dkzzz = TAT_nan()
    qlm_emd_alpha = TAT_nan()
    qlm_emd_betax = TAT_nan()
    qlm_emd_betay = TAT_nan()
    qlm_emd_betaz = TAT_nan()
    qlm_emd_ttt = TAT_nan()
    qlm_emd_ttx = TAT_nan()
    qlm_emd_tty = TAT_nan()
    qlm_emd_ttz = TAT_nan()
    qlm_emd_txx = TAT_nan()
    qlm_emd_txy = TAT_nan()
    qlm_emd_txz = TAT_nan()
    qlm_emd_tyy = TAT_nan()
    qlm_emd_tyz = TAT_nan()
    qlm_emd_tzz = TAT_nan()
    qlm_emd_ex = TAT_nan()
    qlm_emd_ey = TAT_nan()
    qlm_emd_ez = TAT_nan()
    
    qlm_emd_dqttt = TAT_nan()
    qlm_emd_dqtpt = TAT_nan()
    qlm_emd_dqppt = TAT_nan()
    qlm_emd_dqttp = TAT_nan()
    qlm_emd_dqtpp = TAT_nan()
    qlm_emd_dqppp = TAT_nan()
    
    tetrad_derivs_nan%nabla_ll = TAT_nan()
    tetrad_derivs_nan%nabla_nn = TAT_nan()
    tetrad_derivs_nan%nabla_mm = cmplx(TAT_nan(),TAT_nan(),rk)
    qlm_emd_tetrad_derivs = tetrad_derivs_nan

    qlm_emd_spin_density = TAT_nan()
  end subroutine allocate_variables

  subroutine deallocate_variables
    deallocate(qlm_emd_gxx)
    deallocate(qlm_emd_gxy)
    deallocate(qlm_emd_gxz)
    deallocate(qlm_emd_gyy)
    deallocate(qlm_emd_gyz)
    deallocate(qlm_emd_gzz)
    deallocate(qlm_emd_dgxxx)
    deallocate(qlm_emd_dgxyx)
    deallocate(qlm_emd_dgxzx)
    deallocate(qlm_emd_dgyyx)
    deallocate(qlm_emd_dgyzx)
    deallocate(qlm_emd_dgzzx)
    deallocate(qlm_emd_dgxxy)
    deallocate(qlm_emd_dgxyy)
    deallocate(qlm_emd_dgxzy)
    deallocate(qlm_emd_dgyyy)
    deallocate(qlm_emd_dgyzy)
    deallocate(qlm_emd_dgzzy)
    deallocate(qlm_emd_dgxxz)
    deallocate(qlm_emd_dgxyz)
    deallocate(qlm_emd_dgxzz)
    deallocate(qlm_emd_dgyyz)
    deallocate(qlm_emd_dgyzz)
    deallocate(qlm_emd_dgzzz)
    deallocate(qlm_emd_ddgxxxx)
    deallocate(qlm_emd_ddgxyxx)
    deallocate(qlm_emd_ddgxzxx)
    deallocate(qlm_emd_ddgyyxx)
    deallocate(qlm_emd_ddgyzxx)
    deallocate(qlm_emd_ddgzzxx)
    deallocate(qlm_emd_ddgxxxy)
    deallocate(qlm_emd_ddgxyxy)
    deallocate(qlm_emd_ddgxzxy)
    deallocate(qlm_emd_ddgyyxy)
    deallocate(qlm_emd_ddgyzxy)
    deallocate(qlm_emd_ddgzzxy)
    deallocate(qlm_emd_ddgxxxz)
    deallocate(qlm_emd_ddgxyxz)
    deallocate(qlm_emd_ddgxzxz)
    deallocate(qlm_emd_ddgyyxz)
    deallocate(qlm_emd_ddgyzxz)
    deallocate(qlm_emd_ddgzzxz)
    deallocate(qlm_emd_ddgxxyy)
    deallocate(qlm_emd_ddgxyyy)
    deallocate(qlm_emd_ddgxzyy)
    deallocate(qlm_emd_ddgyyyy)
    deallocate(qlm_emd_ddgyzyy)
    deallocate(qlm_emd_ddgzzyy)
    deallocate(qlm_emd_ddgxxyz)
    deallocate(qlm_emd_ddgxyyz)
    deallocate(qlm_emd_ddgxzyz)
    deallocate(qlm_emd_ddgyyyz)
    deallocate(qlm_emd_ddgyzyz)
    deallocate(qlm_emd_ddgzzyz)
    deallocate(qlm_emd_ddgxxzz)
    deallocate(qlm_emd_ddgxyzz)
    deallocate(qlm_emd_ddgxzzz)
    deallocate(qlm_emd_ddgyyzz)
    deallocate(qlm_emd_ddgyzzz)
    deallocate(qlm_emd_ddgzzzz)
    deallocate(qlm_emd_kxx)
    deallocate(qlm_emd_kxy)
    deallocate(qlm_emd_kxz)
    deallocate(qlm_emd_kyy)
    deallocate(qlm_emd_kyz)
    deallocate(qlm_emd_kzz)
    deallocate(qlm_emd_dkxxx)
    deallocate(qlm_emd_dkxyx)
    deallocate(qlm_emd_dkxzx)
    deallocate(qlm_emd_dkyyx)
    deallocate(qlm_emd_dkyzx)
    deallocate(qlm_emd_dkzzx)
    deallocate(qlm_emd_dkxxy)
    deallocate(qlm_emd_dkxyy)
    deallocate(qlm_emd_dkxzy)
    deallocate(qlm_emd_dkyyy)
    deallocate(qlm_emd_dkyzy)
    deallocate(qlm_emd_dkzzy)
    deallocate(qlm_emd_dkxxz)
    deallocate(qlm_emd_dkxyz)
    deallocate(qlm_emd_dkxzz)
    deallocate(qlm_emd_dkyyz)
    deallocate(qlm_emd_dkyzz)
    deallocate(qlm_emd_dkzzz)
    deallocate(qlm_emd_alpha)
    deallocate(qlm_emd_betax)
    deallocate(qlm_emd_betay)
    deallocate(qlm_emd_betaz)
    deallocate(qlm_emd_ttt)
    deallocate(qlm_emd_ttx)
    deallocate(qlm_emd_tty)
    deallocate(qlm_emd_ttz)
    deallocate(qlm_emd_txx)
    deallocate(qlm_emd_txy)
    deallocate(qlm_emd_txz)
    deallocate(qlm_emd_tyy)
    deallocate(qlm_emd_tyz)
    deallocate(qlm_emd_tzz)
    deallocate(qlm_emd_ex)
    deallocate(qlm_emd_ey)
    deallocate(qlm_emd_ez)
    
    deallocate(qlm_emd_dqttt)
    deallocate(qlm_emd_dqtpt)
    deallocate(qlm_emd_dqppt)
    deallocate(qlm_emd_dqttp)
    deallocate(qlm_emd_dqtpp)
    deallocate(qlm_emd_dqppp)
    
    deallocate(qlm_emd_tetrad_derivs)

    deallocate(qlm_emd_spin_density)
  end subroutine deallocate_variables

end module qlm_emd_variables
